version: '3.8'

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: maguireyounes.com
    env_file: .env
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    ports:
      - "25:25"     # SMTP
      - "143:143"   # IMAP
      - "587:587"   # Submission (SMTP Auth)
      - "993:993"   # Secure IMAP
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
    ports:
      - "8080:80"  # Roundcube Webmail UI
    depends_on:
      - mailserver

volumes:
  maildata:
  mailstate:
  maillogs: